// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package messages

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Generic response message providing an error message from remote servers
type Ack struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (m *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(m, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

func (m *Ack) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// Empty message for requesting action from any type of server
type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

// Wrapper for authenticated messages that also ensure integrity
type AuthenticatedMessage struct {
	ID                   []byte    `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Signature            []byte    `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Token                []byte    `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	Client               *ClientID `protobuf:"bytes,4,opt,name=Client,proto3" json:"Client,omitempty"`
	Message              *any.Any  `protobuf:"bytes,5,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AuthenticatedMessage) Reset()         { *m = AuthenticatedMessage{} }
func (m *AuthenticatedMessage) String() string { return proto.CompactTextString(m) }
func (*AuthenticatedMessage) ProtoMessage()    {}
func (*AuthenticatedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *AuthenticatedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticatedMessage.Unmarshal(m, b)
}
func (m *AuthenticatedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticatedMessage.Marshal(b, m, deterministic)
}
func (m *AuthenticatedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticatedMessage.Merge(m, src)
}
func (m *AuthenticatedMessage) XXX_Size() int {
	return xxx_messageInfo_AuthenticatedMessage.Size(m)
}
func (m *AuthenticatedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticatedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticatedMessage proto.InternalMessageInfo

func (m *AuthenticatedMessage) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *AuthenticatedMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *AuthenticatedMessage) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *AuthenticatedMessage) GetClient() *ClientID {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *AuthenticatedMessage) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

// Message used for assembly of Client IDs in the system
type ClientID struct {
	Salt                 []byte   `protobuf:"bytes,1,opt,name=Salt,proto3" json:"Salt,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientID) Reset()         { *m = ClientID{} }
func (m *ClientID) String() string { return proto.CompactTextString(m) }
func (*ClientID) ProtoMessage()    {}
func (*ClientID) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *ClientID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientID.Unmarshal(m, b)
}
func (m *ClientID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientID.Marshal(b, m, deterministic)
}
func (m *ClientID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientID.Merge(m, src)
}
func (m *ClientID) XXX_Size() int {
	return xxx_messageInfo_ClientID.Size(m)
}
func (m *ClientID) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientID.DiscardUnknown(m)
}

var xxx_messageInfo_ClientID proto.InternalMessageInfo

func (m *ClientID) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *ClientID) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

// Provides a token to establish reverse identity to any type of client
type AssignToken struct {
	Token                []byte   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignToken) Reset()         { *m = AssignToken{} }
func (m *AssignToken) String() string { return proto.CompactTextString(m) }
func (*AssignToken) ProtoMessage()    {}
func (*AssignToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *AssignToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignToken.Unmarshal(m, b)
}
func (m *AssignToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignToken.Marshal(b, m, deterministic)
}
func (m *AssignToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignToken.Merge(m, src)
}
func (m *AssignToken) XXX_Size() int {
	return xxx_messageInfo_AssignToken.Size(m)
}
func (m *AssignToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignToken.DiscardUnknown(m)
}

var xxx_messageInfo_AssignToken proto.InternalMessageInfo

func (m *AssignToken) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

// RSASignature is a digital signature for the RSA algorithm
type RSASignature struct {
	Nonce                []byte   `protobuf:"bytes,1,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RSASignature) Reset()         { *m = RSASignature{} }
func (m *RSASignature) String() string { return proto.CompactTextString(m) }
func (*RSASignature) ProtoMessage()    {}
func (*RSASignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}

func (m *RSASignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RSASignature.Unmarshal(m, b)
}
func (m *RSASignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RSASignature.Marshal(b, m, deterministic)
}
func (m *RSASignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RSASignature.Merge(m, src)
}
func (m *RSASignature) XXX_Size() int {
	return xxx_messageInfo_RSASignature.Size(m)
}
func (m *RSASignature) XXX_DiscardUnknown() {
	xxx_messageInfo_RSASignature.DiscardUnknown(m)
}

var xxx_messageInfo_RSASignature proto.InternalMessageInfo

func (m *RSASignature) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *RSASignature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Generic message used for a variety of Gossip protocols
type GossipMsg struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Origin               []byte   `protobuf:"bytes,2,opt,name=Origin,proto3" json:"Origin,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GossipMsg) Reset()         { *m = GossipMsg{} }
func (m *GossipMsg) String() string { return proto.CompactTextString(m) }
func (*GossipMsg) ProtoMessage()    {}
func (*GossipMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{6}
}

func (m *GossipMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GossipMsg.Unmarshal(m, b)
}
func (m *GossipMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GossipMsg.Marshal(b, m, deterministic)
}
func (m *GossipMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GossipMsg.Merge(m, src)
}
func (m *GossipMsg) XXX_Size() int {
	return xxx_messageInfo_GossipMsg.Size(m)
}
func (m *GossipMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GossipMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GossipMsg proto.InternalMessageInfo

func (m *GossipMsg) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *GossipMsg) GetOrigin() []byte {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *GossipMsg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GossipMsg) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*Ack)(nil), "messages.Ack")
	proto.RegisterType((*Ping)(nil), "messages.Ping")
	proto.RegisterType((*AuthenticatedMessage)(nil), "messages.AuthenticatedMessage")
	proto.RegisterType((*ClientID)(nil), "messages.ClientID")
	proto.RegisterType((*AssignToken)(nil), "messages.AssignToken")
	proto.RegisterType((*RSASignature)(nil), "messages.RSASignature")
	proto.RegisterType((*GossipMsg)(nil), "messages.GossipMsg")
}

func init() {
	proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5)
}

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0x5e, 0xda, 0x2e, 0x5d, 0x6f, 0xa5, 0x82, 0xa3, 0xa0, 0x50, 0x10, 0x9a, 0xcc, 0x4b, 0xc5,
	0x43, 0x26, 0x95, 0x49, 0xbc, 0xf0, 0x12, 0xe8, 0x34, 0x55, 0x68, 0x50, 0xa5, 0xfb, 0x03, 0x6e,
	0x6a, 0x8c, 0xd5, 0xd4, 0x2e, 0xb6, 0xf3, 0xd0, 0x7f, 0xc0, 0x2f, 0xe2, 0xf7, 0xa1, 0xd8, 0x49,
	0x93, 0x4d, 0x08, 0xed, 0xcd, 0xdf, 0xdd, 0x77, 0x77, 0xdf, 0x77, 0x67, 0x18, 0xed, 0x98, 0x31,
	0x94, 0x33, 0x13, 0xef, 0xb5, 0xb2, 0x0a, 0xcf, 0x6a, 0x3c, 0x79, 0xc5, 0x95, 0xe2, 0x39, 0xbb,
	0x74, 0xf1, 0x75, 0xf1, 0xe3, 0x92, 0xca, 0x83, 0x27, 0x91, 0xd7, 0xd0, 0x4d, 0xb2, 0x2d, 0x8e,
	0xe1, 0xf4, 0x5a, 0x6b, 0xa5, 0xa3, 0xe0, 0x22, 0x98, 0x0e, 0x52, 0x0f, 0x48, 0x08, 0xbd, 0xa5,
	0x90, 0x9c, 0xfc, 0x09, 0x60, 0x9c, 0x14, 0xf6, 0x27, 0x93, 0x56, 0x64, 0xd4, 0xb2, 0xcd, 0xad,
	0xef, 0x8c, 0x23, 0xe8, 0x2c, 0xe6, 0xae, 0x66, 0x98, 0x76, 0x16, 0x73, 0x7c, 0x03, 0x83, 0x95,
	0xe0, 0x92, 0xda, 0x42, 0xb3, 0xa8, 0xe3, 0xc2, 0x4d, 0xa0, 0x1c, 0x72, 0xa7, 0xb6, 0x4c, 0x46,
	0x5d, 0x97, 0xf1, 0x00, 0xdf, 0x43, 0xf8, 0x25, 0x17, 0x4c, 0xda, 0xa8, 0x77, 0x11, 0x4c, 0xcf,
	0x67, 0x18, 0x1f, 0x7d, 0xf8, 0xf8, 0x62, 0x9e, 0x56, 0x0c, 0x8c, 0xa1, 0x5f, 0x8d, 0x8e, 0x4e,
	0x1d, 0x79, 0x1c, 0x7b, 0x6b, 0x71, 0x6d, 0x2d, 0x4e, 0xe4, 0x21, 0xad, 0x49, 0xe4, 0x13, 0x9c,
	0xd5, 0x3d, 0x10, 0xa1, 0xb7, 0xa2, 0xb9, 0xad, 0xd4, 0xba, 0x77, 0xa9, 0x77, 0x59, 0xac, 0x73,
	0x91, 0x7d, 0x65, 0x07, 0xa7, 0x77, 0x90, 0x36, 0x01, 0xf2, 0x0e, 0xce, 0x13, 0x63, 0x04, 0x97,
	0x5e, 0xe8, 0x51, 0x7e, 0xd0, 0x92, 0x4f, 0x3e, 0xc3, 0x30, 0x5d, 0x25, 0xf7, 0x4c, 0x7e, 0x53,
	0x32, 0x63, 0x35, 0xcb, 0x81, 0xff, 0x2f, 0x86, 0xec, 0x60, 0x70, 0xa3, 0x8c, 0x11, 0xfb, 0x5b,
	0xc3, 0xf1, 0x29, 0x74, 0xef, 0x28, 0xaf, 0x0e, 0x51, 0x3e, 0xf1, 0x25, 0x84, 0xdf, 0xb5, 0xe0,
	0x42, 0x56, 0x95, 0x15, 0xc2, 0x08, 0xfa, 0x4b, 0x7a, 0xc8, 0x15, 0xdd, 0x54, 0x1b, 0xad, 0xe1,
	0xfd, 0x71, 0xbd, 0x07, 0xe3, 0x66, 0xbf, 0x03, 0xe8, 0xdf, 0x30, 0xc9, 0xb4, 0xc8, 0x70, 0x0e,
	0xcf, 0xda, 0x97, 0xf5, 0x4e, 0xdf, 0x36, 0x27, 0xf8, 0xd7, 0xd9, 0x27, 0x4f, 0x5a, 0xf9, 0x6c,
	0x4b, 0x4e, 0xf0, 0x23, 0x0c, 0x53, 0xf6, 0xab, 0x60, 0xc6, 0xfa, 0x06, 0xa3, 0x86, 0x50, 0x7e,
	0xa0, 0xc9, 0x8b, 0x56, 0x41, 0xb3, 0x51, 0x72, 0x32, 0xb3, 0x10, 0x7a, 0xe7, 0x78, 0x05, 0x23,
	0xff, 0xba, 0x96, 0x9b, 0xbd, 0x12, 0xd2, 0xe2, 0xf3, 0xa6, 0xe8, 0xb8, 0x9d, 0x07, 0xa3, 0xf1,
	0x0a, 0x86, 0x3e, 0xb7, 0xb2, 0x9a, 0xd1, 0xdd, 0x63, 0x6a, 0xa6, 0xc1, 0x3a, 0x74, 0xbf, 0xe5,
	0xc3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x98, 0x05, 0x2a, 0x32, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GenericClient is the client API for Generic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GenericClient interface {
	// Authenticate a token with the server
	AuthenticateToken(ctx context.Context, in *AuthenticatedMessage, opts ...grpc.CallOption) (*Ack, error)
	// Request a token from the server
	RequestToken(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*AssignToken, error)
}

type genericClient struct {
	cc grpc.ClientConnInterface
}

func NewGenericClient(cc grpc.ClientConnInterface) GenericClient {
	return &genericClient{cc}
}

func (c *genericClient) AuthenticateToken(ctx context.Context, in *AuthenticatedMessage, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/messages.Generic/AuthenticateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genericClient) RequestToken(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*AssignToken, error) {
	out := new(AssignToken)
	err := c.cc.Invoke(ctx, "/messages.Generic/RequestToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenericServer is the server API for Generic service.
type GenericServer interface {
	// Authenticate a token with the server
	AuthenticateToken(context.Context, *AuthenticatedMessage) (*Ack, error)
	// Request a token from the server
	RequestToken(context.Context, *Ping) (*AssignToken, error)
}

// UnimplementedGenericServer can be embedded to have forward compatible implementations.
type UnimplementedGenericServer struct {
}

func (*UnimplementedGenericServer) AuthenticateToken(ctx context.Context, req *AuthenticatedMessage) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateToken not implemented")
}
func (*UnimplementedGenericServer) RequestToken(ctx context.Context, req *Ping) (*AssignToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestToken not implemented")
}

func RegisterGenericServer(s *grpc.Server, srv GenericServer) {
	s.RegisterService(&_Generic_serviceDesc, srv)
}

func _Generic_AuthenticateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticatedMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenericServer).AuthenticateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Generic/AuthenticateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenericServer).AuthenticateToken(ctx, req.(*AuthenticatedMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Generic_RequestToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenericServer).RequestToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Generic/RequestToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenericServer).RequestToken(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

var _Generic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "messages.Generic",
	HandlerType: (*GenericServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthenticateToken",
			Handler:    _Generic_AuthenticateToken_Handler,
		},
		{
			MethodName: "RequestToken",
			Handler:    _Generic_RequestToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}

// GossipClient is the client API for Gossip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GossipClient interface {
	GossipEndpoint(ctx context.Context, in *GossipMsg, opts ...grpc.CallOption) (*Ack, error)
	GossipStream(ctx context.Context, opts ...grpc.CallOption) (Gossip_GossipStreamClient, error)
}

type gossipClient struct {
	cc grpc.ClientConnInterface
}

func NewGossipClient(cc grpc.ClientConnInterface) GossipClient {
	return &gossipClient{cc}
}

func (c *gossipClient) GossipEndpoint(ctx context.Context, in *GossipMsg, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/messages.Gossip/GossipEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipClient) GossipStream(ctx context.Context, opts ...grpc.CallOption) (Gossip_GossipStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Gossip_serviceDesc.Streams[0], "/messages.Gossip/GossipStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &gossipGossipStreamClient{stream}
	return x, nil
}

type Gossip_GossipStreamClient interface {
	Send(*GossipMsg) error
	CloseAndRecv() (*Ack, error)
	grpc.ClientStream
}

type gossipGossipStreamClient struct {
	grpc.ClientStream
}

func (x *gossipGossipStreamClient) Send(m *GossipMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gossipGossipStreamClient) CloseAndRecv() (*Ack, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Ack)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GossipServer is the server API for Gossip service.
type GossipServer interface {
	GossipEndpoint(context.Context, *GossipMsg) (*Ack, error)
	GossipStream(Gossip_GossipStreamServer) error
}

// UnimplementedGossipServer can be embedded to have forward compatible implementations.
type UnimplementedGossipServer struct {
}

func (*UnimplementedGossipServer) GossipEndpoint(ctx context.Context, req *GossipMsg) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GossipEndpoint not implemented")
}
func (*UnimplementedGossipServer) GossipStream(srv Gossip_GossipStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GossipStream not implemented")
}

func RegisterGossipServer(s *grpc.Server, srv GossipServer) {
	s.RegisterService(&_Gossip_serviceDesc, srv)
}

func _Gossip_GossipEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).GossipEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Gossip/GossipEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).GossipEndpoint(ctx, req.(*GossipMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gossip_GossipStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GossipServer).GossipStream(&gossipGossipStreamServer{stream})
}

type Gossip_GossipStreamServer interface {
	SendAndClose(*Ack) error
	Recv() (*GossipMsg, error)
	grpc.ServerStream
}

type gossipGossipStreamServer struct {
	grpc.ServerStream
}

func (x *gossipGossipStreamServer) SendAndClose(m *Ack) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gossipGossipStreamServer) Recv() (*GossipMsg, error) {
	m := new(GossipMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Gossip_serviceDesc = grpc.ServiceDesc{
	ServiceName: "messages.Gossip",
	HandlerType: (*GossipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GossipEndpoint",
			Handler:    _Gossip_GossipEndpoint_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GossipStream",
			Handler:       _Gossip_GossipStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "messages.proto",
}
